CREATE DATABASE HOSTEL_DETAILS;
USE HOSTEL_DETAILS;
CREATE TABLE INFO(ID INT,NAME_PERSON VARCHAR (20),FEES BIGINT,PHONE_NO BIGINT);
INSERT INTO INFO VALUES(65,"REVATI",508155,8123791097);
select *FROM INFO;
CREATE DATABASE VEGITABLE_INFO;
USE VEGITABLE_INFO;
CREATE TABLE INFO_VEG(ID BIGINT,VEG_NAME VARCHAR (15),PRICE BIGINT,QUALITY VARCHAR(10),QUANTITY INT,USE_VEG VARCHAR(20),TYPE_VEG VARCHAR(10),BAG INT);

CREATE TABLE PERSON(ID INT,NAME_PERSON VARCHAR(10),ADDRESS VARCHAR(20),PHONENO BIGINT,PINCODE BIGINT,STATE VARCHAR(10),NATIONALITY VARCHAR(20),AGE INT);

CREATE TABLE SCHOOL(ID INT, NAME_STUDENT VARCHAR(10),FATHER_NAME VARCHAR(10),MATHER_NAME VARCHAR(20),ADDRESS VARCHAR(20),USN BIGINT,FEES BIGINT,AGE INT);

CREATE TABLE SHOP(ID INT,DRESS_NAME VARCHAR(10), DRESS_TYPE VARCHAR(20),MATERIALS VARCHAR(20),DRESS_COLOR VARCHAR(20),DRESS_CODE INT,DRESS_PRICE BIGINT,GST BIGINT);

CREATE TABLE SOAP (ID INT,CODE_SOAP INT,SOAP_NAME VARCHAR(10),FRAGRANCE VARCHAR(10),BRAND VARCHAR(20),SHAP VARCHAR(10),PRICE BIGINT,DISCOUNT BIGINT);
USE VEGITABLE_INFO;
ALTER TABLE SOAP ADD COLUMN MGF_BY VARCHAR(20);
ALTER TABLE SHOP ADD COLUMN ADD_SHOP VARCHAR(20);
ALTER TABLE SCHOOL ADD COLUMN NO_OF_STUDENT INT;


