USE REVU;
CREATE TABLE AIRPORT_DETAILS(ID INT,NAME_PER VARCHAR(20),ADD_PER VARCHAR(20));
ALTER TABLE AIRPORT_DETAILS ADD COLUMN PHONE_NO BIGINT;
ALTER TABLE AIRPORT_DETAILS ADD COLUMN ADHAR VARCHAR(10);
ALTER TABLE AIRPORT_DETAILS ADD COLUMN PASPORT_NO INT;
ALTER TABLE AIRPORT_DETAILS ADD COLUMN CITY VARCHAR(10);
ALTER TABLE AIRPORT_DETAILS ADD COLUMN PINCODE BIGINT;
ALTER TABLE AIRPORT_DETAILS ADD COLUMN VISA BIGINT;
ALTER TABLE AIRPORT_DETAILS ADD COLUMN BAG_WEIGHT INT;

ALTER TABLE AIRPORT_DETAILS DROP COLUMN ADD_PER;
ALTER TABLE AIRPORT_DETAILS DROP COLUMN PHONE_NO;

ALTER TABLE AIRPORT_DETAILS RENAME COLUMN CITY TO NEW_CURRENT_CITY;
ALTER TABLE AIRPORT_DETAILS RENAME COLUMN NAME_PER TO PER_NAME;
ALTER TABLE AIRPORT_DETAILS RENAME COLUMN ADHAR TO ADHAR_NO;
ALTER TABLE AIRPORT_DETAILS RENAME COLUMN PINCODE TO CITY_PINCODE;
ALTER TABLE AIRPORT_DETAILS RENAME COLUMN PASPORT_NO TO PASSPORT;

ALTER TABLE AIRPORT_DETAILS MODIFY COLUMN ID BIGINT;
ALTER TABLE AIRPORT_DETAILS MODIFY COLUMN PASSPORT BIGINT;
ALTER TABLE AIRPORT_DETAILS MODIFY COLUMN CITY_PINCODE INT;
ALTER TABLE AIRPORT_DETAILS MODIFY COLUMN PHONE_NO INT;
ALTER TABLE AIRPORT_DETAILS MODIFY COLUMN VISA  INT;

DESC AIRPORT_DETAILS;









